apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: us-central1-docker.pkg.dev/worstation-379213/argocd-clouddeploy-repo/argocd-clouddeploy-app
  newName: us-central1-docker.pkg.dev/worstation-379213/argocd-clouddeploy-repo/argocd-clouddeploy-app
  newTag: dev-1.0.0