# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argocd-clouddeploy-app-service
spec:
  selector:
    app: argocd-clouddeploy-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer